name: Sync Airtable & Deploy

on:
  # Run on schedule (daily at 6 AM UTC)
  schedule:
    - cron: '0 6 * * *'
  
  # Run on manual trigger
  workflow_dispatch:
  
  # Run on push to main branch
  push:
    branches: [ main ]
  
  # Run on pull request
  pull_request:
    branches: [ main ]

  repository_dispatch:
    types: [airtable-sync]

env:
  NODE_VERSION: '18'
  PYTHON_VERSION: '3.11'

jobs:
  sync-and-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        fetch-depth: 0
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
        cache: 'pip'
    
    - name: Install Node.js dependencies
      run: npm ci
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Configure Git
      run: |
        git config --global user.name "Airtable Sync Bot"
        git config --global user.email "sync@aiconference2024.com"
    
    - name: Sync from Airtable
      env:
        AIRTABLE_API_KEY: ${{ secrets.AIRTABLE_API_KEY }}
        AIRTABLE_BASE_ID: ${{ secrets.AIRTABLE_BASE_ID }}
        AIRTABLE_TABLE_NAME: ${{ secrets.AIRTABLE_TABLE_NAME }}
      run: |
        python scripts/sync_airtable.py
        
        # Check if there are any changes
        if [[ -n $(git status --porcelain) ]]; then
          echo "Changes detected from Airtable sync"
          echo "HAS_CHANGES=true" >> $GITHUB_ENV
        else
          echo "No changes from Airtable sync"
          echo "HAS_CHANGES=false" >> $GITHUB_ENV
        fi
    
    - name: Build Tailwind CSS
      run: |
        npx tailwindcss -i src/input.css -o src/css/style.css --minify
    
    - name: Build Eleventy site
      run: |
        npm run build
    
    - name: Commit and push changes
      if: env.HAS_CHANGES == 'true' && github.event_name != 'pull_request'
      run: |
        git add .
        git commit -m "Auto-sync from Airtable - $(date '+%Y-%m-%d %H:%M:%S')" || exit 0
        git push origin main
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: site-build
        path: _site/
        retention-days: 30
    
    # Deploy to GitHub Pages (if enabled)
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site
        cname: aiconference2024.com  # Replace with your domain
    
    # Optional: Deploy to Netlify
    - name: Deploy to Netlify
      if: github.ref == 'refs/heads/main' && github.event_name != 'pull_request'
      uses: nwtgck/actions-netlify@v2.1
      with:
        publish-dir: './_site'
        production-branch: main
        github-token: ${{ secrets.GITHUB_TOKEN }}
        deploy-message: "Deploy from GitHub Actions - ${{ github.sha }}"
        enable-pull-request-comment: false
        enable-commit-comment: true
        overwrites-pull-request-comment: true
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

  lighthouse:
    runs-on: ubuntu-latest
    needs: sync-and-build
    if: github.event_name == 'pull_request'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: site-build
          path: _site/

      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v10
        with:
          configPath: '.lighthouserc.json'
          uploadArtifacts: true
          temporaryPublicStorage: true 